### ISSUE TITLE
pip install pyansys does not work

### ISSUE THREAD

**Issue by pmaroneh** [pyansys/pyansys#202]
### Description of the modifications

This [page ](https://docs.pyansys.com/version/dev/getting_started.html) mentions that all pyansys packages can be installed thanks to pip install pyansys, but this command does not work:
![image](https://user-images.githubusercontent.com/76440649/228204623-ed148c64-04f0-431d-85c4-ae79f1774ad7.png)
Also the error messages does not return instructions for installation of all pyansys packages (pydpf core and post, pyprime mesh, etc), I don't know if this is wanted.

**Comment by RobPasMue** [comment]
Hi @pmaroneh! Problem was related to previously existing ``pyansys`` metapackage (old package name for ``pymapdl``). We yanked all previous versions so that this problem no longer appears. No need to do anything else IMO. The command should now work (or at least provide you with some potential incompatibility).

Pinging @akaszynski for visibility
